[2024-04-28T18:32:21.814+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-28T18:32:22.090+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_processing_dag.process_csv_files manual__2024-04-28T18:31:28.467058+00:00 [queued]>
[2024-04-28T18:32:22.147+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_processing_dag.process_csv_files manual__2024-04-28T18:31:28.467058+00:00 [queued]>
[2024-04-28T18:32:22.151+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-28T18:32:22.249+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): process_csv_files> on 2024-04-28 18:31:28.467058+00:00
[2024-04-28T18:32:22.348+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=784) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-28T18:32:22.362+0000] {standard_task_runner.py:63} INFO - Started process 793 to run task
[2024-04-28T18:32:22.366+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_processing_dag', 'process_csv_files', 'manual__2024-04-28T18:31:28.467058+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpui_esdss']
[2024-04-28T18:32:22.378+0000] {standard_task_runner.py:91} INFO - Job 107: Subtask process_csv_files
[2024-04-28T18:32:22.601+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_processing_dag.process_csv_files manual__2024-04-28T18:31:28.467058+00:00 [running]> on host 4cdb6c1dd19f
[2024-04-28T18:32:22.943+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_processing_dag' AIRFLOW_CTX_TASK_ID='process_csv_files' AIRFLOW_CTX_EXECUTION_DATE='2024-04-28T18:31:28.467058+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-28T18:31:28.467058+00:00'
[2024-04-28T18:32:22.945+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-28T18:32:23.760+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-28T18:32:23.762+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-28T18:32:23.780+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=csv_processing_dag, task_id=process_csv_files, execution_date=20240428T183128, start_date=20240428T183222, end_date=20240428T183223
[2024-04-28T18:32:23.835+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-28T18:32:23.868+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-28T18:32:23.876+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
