[2024-04-27T17:51:09.724+0000] {processor.py:161} INFO - Started process (PID=352) to work on /opt/airflow/dags/csv_dag.py
[2024-04-27T17:51:09.726+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/csv_dag.py for tasks to queue
[2024-04-27T17:51:09.729+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:51:09.727+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:51:09.891+0000] {processor.py:840} INFO - DAG(s) 'csv_transform_copy' retrieved from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:51:10.655+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:51:10.648+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-27T17:51:10.680+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:51:10.680+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_transform_copy to None, run_after=None
[2024-04-27T17:51:10.756+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/csv_dag.py took 1.054 seconds
[2024-04-27T17:51:41.646+0000] {processor.py:161} INFO - Started process (PID=359) to work on /opt/airflow/dags/csv_dag.py
[2024-04-27T17:51:41.653+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/csv_dag.py for tasks to queue
[2024-04-27T17:51:41.659+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:51:41.655+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:51:41.746+0000] {processor.py:840} INFO - DAG(s) 'csv_transform_copy' retrieved from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:51:41.930+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:51:41.930+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-27T17:51:41.963+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:51:41.962+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_transform_copy to None, run_after=None
[2024-04-27T17:51:42.001+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/csv_dag.py took 0.376 seconds
[2024-04-27T17:52:12.154+0000] {processor.py:161} INFO - Started process (PID=365) to work on /opt/airflow/dags/csv_dag.py
[2024-04-27T17:52:12.171+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/csv_dag.py for tasks to queue
[2024-04-27T17:52:12.189+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:52:12.182+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:52:12.358+0000] {processor.py:840} INFO - DAG(s) 'csv_transform_copy' retrieved from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:52:27.812+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:52:27.805+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-27T17:52:27.848+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:52:27.848+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_transform_copy to None, run_after=None
[2024-04-27T17:52:27.900+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/csv_dag.py took 15.775 seconds
[2024-04-27T17:52:58.762+0000] {processor.py:161} INFO - Started process (PID=372) to work on /opt/airflow/dags/csv_dag.py
[2024-04-27T17:52:58.765+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/csv_dag.py for tasks to queue
[2024-04-27T17:52:58.767+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:52:58.765+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:52:58.826+0000] {processor.py:840} INFO - DAG(s) 'csv_transform_copy' retrieved from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:52:59.135+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:52:59.134+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-27T17:52:59.168+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:52:59.168+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_transform_copy to None, run_after=None
[2024-04-27T17:52:59.217+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/csv_dag.py took 0.475 seconds
[2024-04-27T17:53:29.683+0000] {processor.py:161} INFO - Started process (PID=379) to work on /opt/airflow/dags/csv_dag.py
[2024-04-27T17:53:29.707+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/csv_dag.py for tasks to queue
[2024-04-27T17:53:29.894+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:53:29.805+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:53:30.739+0000] {processor.py:840} INFO - DAG(s) 'csv_transform_copy' retrieved from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:53:41.552+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:53:41.536+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-27T17:53:41.607+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:53:41.606+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_transform_copy to None, run_after=None
[2024-04-27T17:53:41.686+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/csv_dag.py took 12.269 seconds
[2024-04-27T17:54:14.475+0000] {processor.py:161} INFO - Started process (PID=387) to work on /opt/airflow/dags/csv_dag.py
[2024-04-27T17:54:14.489+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/csv_dag.py for tasks to queue
[2024-04-27T17:54:14.498+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:54:14.495+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:54:14.684+0000] {processor.py:840} INFO - DAG(s) 'csv_transform_copy' retrieved from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:54:15.411+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:54:15.410+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-27T17:54:15.450+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:54:15.449+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_transform_copy to None, run_after=None
[2024-04-27T17:54:15.494+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/csv_dag.py took 1.145 seconds
[2024-04-27T17:54:23.543+0000] {processor.py:161} INFO - Started process (PID=394) to work on /opt/airflow/dags/csv_dag.py
[2024-04-27T17:54:23.545+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/csv_dag.py for tasks to queue
[2024-04-27T17:54:23.548+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:54:23.546+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:54:23.620+0000] {processor.py:840} INFO - DAG(s) 'csv_transform_copy' retrieved from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:54:24.035+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:54:24.035+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-27T17:54:24.074+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:54:24.074+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_transform_copy to None, run_after=None
[2024-04-27T17:54:25.977+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/csv_dag.py took 2.442 seconds
[2024-04-27T17:54:56.274+0000] {processor.py:161} INFO - Started process (PID=401) to work on /opt/airflow/dags/csv_dag.py
[2024-04-27T17:54:56.277+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/csv_dag.py for tasks to queue
[2024-04-27T17:54:56.279+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:54:56.278+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:54:56.334+0000] {processor.py:840} INFO - DAG(s) 'csv_transform_copy' retrieved from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:54:56.513+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:54:56.513+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-27T17:54:56.542+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:54:56.542+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_transform_copy to None, run_after=None
[2024-04-27T17:54:56.586+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/csv_dag.py took 0.326 seconds
[2024-04-27T17:55:27.418+0000] {processor.py:161} INFO - Started process (PID=408) to work on /opt/airflow/dags/csv_dag.py
[2024-04-27T17:55:27.631+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/csv_dag.py for tasks to queue
[2024-04-27T17:55:27.949+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:55:27.649+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:55:29.581+0000] {processor.py:840} INFO - DAG(s) 'csv_transform_copy' retrieved from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:55:33.255+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:55:33.254+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-27T17:55:33.296+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:55:33.295+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_transform_copy to None, run_after=None
[2024-04-27T17:55:33.335+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/csv_dag.py took 6.337 seconds
[2024-04-27T17:55:58.648+0000] {processor.py:161} INFO - Started process (PID=409) to work on /opt/airflow/dags/csv_dag.py
[2024-04-27T17:55:58.667+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/csv_dag.py for tasks to queue
[2024-04-27T17:55:58.694+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:55:58.682+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:55:59.845+0000] {processor.py:840} INFO - DAG(s) 'csv_transform_copy' retrieved from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:56:02.446+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:56:02.422+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'csv_transform_copy', 'Task Id': 'transform_csv', 'Run Id': 'manual__2024-04-27T17:49:43.618209+00:00', 'Hostname': 'ff7143738b80', 'External Executor Id': '9ab4ff5c-6daa-4155-ab3e-94b804778f1d'}
[2024-04-27T17:56:02.681+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:56:02.680+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=csv_transform_copy, task_id=transform_csv, execution_date=20240427T174943, start_date=20240427T175520, end_date=20240427T175602
[2024-04-27T17:56:02.800+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: csv_transform_copy.transform_csv manual__2024-04-27T17:49:43.618209+00:00 [failed]> in state failed
[2024-04-27T17:56:06.075+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:56:06.074+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-27T17:56:06.183+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:56:06.182+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_transform_copy to None, run_after=None
[2024-04-27T17:56:06.358+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/csv_dag.py took 8.309 seconds
[2024-04-27T17:56:37.295+0000] {processor.py:161} INFO - Started process (PID=423) to work on /opt/airflow/dags/csv_dag.py
[2024-04-27T17:56:37.325+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/csv_dag.py for tasks to queue
[2024-04-27T17:56:37.381+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:56:37.356+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:56:37.988+0000] {processor.py:840} INFO - DAG(s) 'csv_transform_copy' retrieved from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:56:55.493+0000] {processor.py:715} ERROR - Error executing TaskCallbackRequest callback for file: /opt/airflow/dags/csv_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 709, in execute_callbacks
    self._execute_task_callbacks(dagbag, request, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 762, in _execute_task_callbacks
    ti = TaskInstance.get_task_instance(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1804, in get_task_instance
    return query.one_or_none()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2850, in one_or_none
    return self._iter().one_or_none()
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-04-27T17:56:57.630+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:56:57.629+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-27T17:56:57.697+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:56:57.697+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_transform_copy to None, run_after=None
[2024-04-27T17:56:57.782+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/csv_dag.py took 20.606 seconds
[2024-04-27T17:57:28.335+0000] {processor.py:161} INFO - Started process (PID=430) to work on /opt/airflow/dags/csv_dag.py
[2024-04-27T17:57:28.349+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/csv_dag.py for tasks to queue
[2024-04-27T17:57:28.354+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:57:28.352+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:57:28.403+0000] {processor.py:840} INFO - DAG(s) 'csv_transform_copy' retrieved from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:57:28.456+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:57:28.455+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-27T17:57:28.478+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:57:28.477+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_transform_copy to None, run_after=None
[2024-04-27T17:57:28.512+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/csv_dag.py took 0.220 seconds
[2024-04-27T17:57:58.653+0000] {processor.py:161} INFO - Started process (PID=437) to work on /opt/airflow/dags/csv_dag.py
[2024-04-27T17:57:58.656+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/csv_dag.py for tasks to queue
[2024-04-27T17:57:58.657+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:57:58.657+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:57:58.695+0000] {processor.py:840} INFO - DAG(s) 'csv_transform_copy' retrieved from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:57:58.741+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:57:58.740+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-27T17:57:58.755+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:57:58.754+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_transform_copy to None, run_after=None
[2024-04-27T17:57:58.783+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/csv_dag.py took 0.138 seconds
[2024-04-27T17:58:29.167+0000] {processor.py:161} INFO - Started process (PID=444) to work on /opt/airflow/dags/csv_dag.py
[2024-04-27T17:58:29.169+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/csv_dag.py for tasks to queue
[2024-04-27T17:58:29.170+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:58:29.170+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:58:29.207+0000] {processor.py:840} INFO - DAG(s) 'csv_transform_copy' retrieved from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:58:29.250+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:58:29.245+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-27T17:58:29.266+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:58:29.265+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_transform_copy to None, run_after=None
[2024-04-27T17:58:29.287+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/csv_dag.py took 0.126 seconds
[2024-04-27T17:58:59.553+0000] {processor.py:161} INFO - Started process (PID=452) to work on /opt/airflow/dags/csv_dag.py
[2024-04-27T17:58:59.554+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/csv_dag.py for tasks to queue
[2024-04-27T17:58:59.556+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:58:59.555+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:58:59.605+0000] {processor.py:840} INFO - DAG(s) 'csv_transform_copy' retrieved from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:58:59.660+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:58:59.660+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-27T17:58:59.674+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:58:59.673+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_transform_copy to None, run_after=None
[2024-04-27T17:58:59.705+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/csv_dag.py took 0.158 seconds
[2024-04-27T17:59:14.714+0000] {processor.py:161} INFO - Started process (PID=459) to work on /opt/airflow/dags/csv_dag.py
[2024-04-27T17:59:14.735+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/csv_dag.py for tasks to queue
[2024-04-27T17:59:14.739+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:59:14.738+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:59:21.133+0000] {processor.py:840} INFO - DAG(s) 'csv_transform_copy' retrieved from /opt/airflow/dags/csv_dag.py
[2024-04-27T17:59:38.106+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:59:38.096+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-27T17:59:38.140+0000] {logging_mixin.py:188} INFO - [2024-04-27T17:59:38.140+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_transform_copy to None, run_after=None
[2024-04-27T17:59:38.215+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/csv_dag.py took 23.535 seconds
[2024-04-27T18:00:08.688+0000] {processor.py:161} INFO - Started process (PID=468) to work on /opt/airflow/dags/csv_dag.py
[2024-04-27T18:00:08.692+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/csv_dag.py for tasks to queue
[2024-04-27T18:00:08.697+0000] {logging_mixin.py:188} INFO - [2024-04-27T18:00:08.695+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/csv_dag.py
[2024-04-27T18:00:33.836+0000] {processor.py:840} INFO - DAG(s) 'csv_transform_copy' retrieved from /opt/airflow/dags/csv_dag.py
[2024-04-27T18:00:34.162+0000] {logging_mixin.py:188} INFO - [2024-04-27T18:00:34.156+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-27T18:00:34.209+0000] {logging_mixin.py:188} INFO - [2024-04-27T18:00:34.208+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_transform_copy to None, run_after=None
[2024-04-27T18:00:34.270+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/csv_dag.py took 25.045 seconds
[2024-04-27T18:01:04.789+0000] {processor.py:161} INFO - Started process (PID=482) to work on /opt/airflow/dags/csv_dag.py
[2024-04-27T18:01:04.790+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/csv_dag.py for tasks to queue
[2024-04-27T18:01:04.795+0000] {logging_mixin.py:188} INFO - [2024-04-27T18:01:04.792+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/csv_dag.py
[2024-04-27T18:01:06.279+0000] {processor.py:840} INFO - DAG(s) 'csv_transform_copy' retrieved from /opt/airflow/dags/csv_dag.py
[2024-04-27T18:01:37.448+0000] {logging_mixin.py:188} INFO - [2024-04-27T18:01:37.445+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-27T18:01:37.482+0000] {logging_mixin.py:188} INFO - [2024-04-27T18:01:37.481+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_transform_copy to None, run_after=None
[2024-04-27T18:01:37.568+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/csv_dag.py took 32.397 seconds
[2024-04-27T18:02:08.200+0000] {processor.py:161} INFO - Started process (PID=496) to work on /opt/airflow/dags/csv_dag.py
[2024-04-27T18:02:08.205+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/csv_dag.py for tasks to queue
[2024-04-27T18:02:08.211+0000] {logging_mixin.py:188} INFO - [2024-04-27T18:02:08.209+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/csv_dag.py
[2024-04-27T18:02:38.710+0000] {processor.py:840} INFO - DAG(s) 'csv_transform_copy' retrieved from /opt/airflow/dags/csv_dag.py
[2024-04-27T18:02:40.585+0000] {logging_mixin.py:188} INFO - [2024-04-27T18:02:40.583+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-27T18:02:40.612+0000] {logging_mixin.py:188} INFO - [2024-04-27T18:02:40.612+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_transform_copy to None, run_after=None
[2024-04-27T18:02:40.682+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/csv_dag.py took 32.285 seconds
[2024-04-27T18:03:11.293+0000] {processor.py:161} INFO - Started process (PID=510) to work on /opt/airflow/dags/csv_dag.py
[2024-04-27T18:03:11.295+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/csv_dag.py for tasks to queue
[2024-04-27T18:03:11.297+0000] {logging_mixin.py:188} INFO - [2024-04-27T18:03:11.296+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/csv_dag.py
[2024-04-27T18:03:12.624+0000] {processor.py:840} INFO - DAG(s) 'csv_transform_copy' retrieved from /opt/airflow/dags/csv_dag.py
[2024-04-27T18:03:12.725+0000] {logging_mixin.py:188} INFO - [2024-04-27T18:03:12.722+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-27T18:03:12.740+0000] {logging_mixin.py:188} INFO - [2024-04-27T18:03:12.740+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_transform_copy to None, run_after=None
[2024-04-27T18:03:12.768+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/csv_dag.py took 1.493 seconds
[2024-04-27T18:03:41.953+0000] {processor.py:161} INFO - Started process (PID=518) to work on /opt/airflow/dags/csv_dag.py
[2024-04-27T18:03:41.956+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/csv_dag.py for tasks to queue
[2024-04-27T18:03:41.961+0000] {logging_mixin.py:188} INFO - [2024-04-27T18:03:41.958+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/csv_dag.py
[2024-04-27T18:03:44.886+0000] {processor.py:840} INFO - DAG(s) 'csv_transform_copy' retrieved from /opt/airflow/dags/csv_dag.py
[2024-04-27T18:03:45.155+0000] {logging_mixin.py:188} INFO - [2024-04-27T18:03:45.155+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-27T18:03:45.168+0000] {logging_mixin.py:188} INFO - [2024-04-27T18:03:45.168+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_transform_copy to None, run_after=None
[2024-04-27T18:03:45.201+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/csv_dag.py took 3.279 seconds
[2024-04-27T18:04:15.925+0000] {processor.py:161} INFO - Started process (PID=520) to work on /opt/airflow/dags/csv_dag.py
[2024-04-27T18:04:15.928+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/csv_dag.py for tasks to queue
[2024-04-27T18:04:15.931+0000] {logging_mixin.py:188} INFO - [2024-04-27T18:04:15.929+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/csv_dag.py
[2024-04-27T18:04:17.367+0000] {processor.py:840} INFO - DAG(s) 'csv_transform_copy' retrieved from /opt/airflow/dags/csv_dag.py
[2024-04-27T18:04:17.408+0000] {logging_mixin.py:188} INFO - [2024-04-27T18:04:17.405+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-27T18:04:17.420+0000] {logging_mixin.py:188} INFO - [2024-04-27T18:04:17.420+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_transform_copy to None, run_after=None
[2024-04-27T18:04:17.451+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/csv_dag.py took 1.545 seconds
[2024-04-27T18:04:26.379+0000] {processor.py:161} INFO - Started process (PID=527) to work on /opt/airflow/dags/csv_dag.py
[2024-04-27T18:04:26.380+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/csv_dag.py for tasks to queue
[2024-04-27T18:04:26.382+0000] {logging_mixin.py:188} INFO - [2024-04-27T18:04:26.381+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/csv_dag.py
[2024-04-27T18:04:27.332+0000] {processor.py:840} INFO - DAG(s) 'csv_transform_copy' retrieved from /opt/airflow/dags/csv_dag.py
[2024-04-27T18:04:27.366+0000] {logging_mixin.py:188} INFO - [2024-04-27T18:04:27.364+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'csv_transform_copy', 'Task Id': 'process_csv', 'Run Id': 'manual__2024-04-27T18:03:45.982335+00:00', 'Hostname': 'ff7143738b80', 'External Executor Id': '05f7498c-7c51-4efd-bd05-3ebf31775eee'}
[2024-04-27T18:04:27.397+0000] {logging_mixin.py:188} INFO - [2024-04-27T18:04:27.396+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=csv_transform_copy, task_id=process_csv, execution_date=20240427T180345, start_date=20240427T180357, end_date=20240427T180427
[2024-04-27T18:04:27.406+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: csv_transform_copy.process_csv manual__2024-04-27T18:03:45.982335+00:00 [up_for_retry]> in state up_for_retry
[2024-04-27T18:04:27.429+0000] {logging_mixin.py:188} INFO - [2024-04-27T18:04:27.428+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-27T18:04:27.440+0000] {logging_mixin.py:188} INFO - [2024-04-27T18:04:27.439+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_transform_copy to None, run_after=None
[2024-04-27T18:04:27.460+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/csv_dag.py took 1.091 seconds
[2024-04-27T18:04:57.725+0000] {processor.py:161} INFO - Started process (PID=535) to work on /opt/airflow/dags/csv_dag.py
[2024-04-27T18:04:57.728+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/csv_dag.py for tasks to queue
[2024-04-27T18:04:57.730+0000] {logging_mixin.py:188} INFO - [2024-04-27T18:04:57.729+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/csv_dag.py
[2024-04-27T18:04:58.640+0000] {processor.py:840} INFO - DAG(s) 'csv_transform_copy' retrieved from /opt/airflow/dags/csv_dag.py
[2024-04-27T18:04:58.679+0000] {logging_mixin.py:188} INFO - [2024-04-27T18:04:58.678+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-27T18:04:58.691+0000] {logging_mixin.py:188} INFO - [2024-04-27T18:04:58.690+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_transform_copy to None, run_after=None
[2024-04-27T18:04:58.718+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/csv_dag.py took 1.000 seconds
[2024-04-27T18:05:29.101+0000] {processor.py:161} INFO - Started process (PID=543) to work on /opt/airflow/dags/csv_dag.py
[2024-04-27T18:05:29.103+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/csv_dag.py for tasks to queue
[2024-04-27T18:05:29.107+0000] {logging_mixin.py:188} INFO - [2024-04-27T18:05:29.105+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/csv_dag.py
[2024-04-27T18:05:30.304+0000] {processor.py:840} INFO - DAG(s) 'csv_transform_copy' retrieved from /opt/airflow/dags/csv_dag.py
[2024-04-27T18:05:30.406+0000] {logging_mixin.py:188} INFO - [2024-04-27T18:05:30.406+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-27T18:05:30.426+0000] {logging_mixin.py:188} INFO - [2024-04-27T18:05:30.425+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_transform_copy to None, run_after=None
[2024-04-27T18:05:30.456+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/csv_dag.py took 1.367 seconds
[2024-04-27T18:06:02.488+0000] {processor.py:161} INFO - Started process (PID=551) to work on /opt/airflow/dags/csv_dag.py
[2024-04-27T18:06:02.595+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/csv_dag.py for tasks to queue
[2024-04-27T18:06:02.693+0000] {logging_mixin.py:188} INFO - [2024-04-27T18:06:02.667+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/csv_dag.py
[2024-04-27T18:06:11.511+0000] {processor.py:840} INFO - DAG(s) 'csv_transform_copy' retrieved from /opt/airflow/dags/csv_dag.py
[2024-04-27T18:06:42.081+0000] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 859, in process_file
    serialize_errors = DagFileProcessor.save_dag_to_db(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 895, in save_dag_to_db
    import_errors = DagBag._sync_to_db(dags=dags, processor_subdir=dag_directory, session=session)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 659, in _sync_to_db
    for attempt in run_with_db_retries(logger=log):
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 672, in _sync_to_db
    _serialize_dag_capturing_errors(dag, session, processor_subdir)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 637, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/serialized_dag.py", line 158, in write_dag
    if session.scalar(
       ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
