[2024-04-28T17:40:38.268+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-28T17:40:38.298+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_processing_dag.process_csv_files manual__2024-04-28T17:35:29.421487+00:00 [queued]>
[2024-04-28T17:40:38.308+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_processing_dag.process_csv_files manual__2024-04-28T17:35:29.421487+00:00 [queued]>
[2024-04-28T17:40:38.309+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-04-28T17:40:38.324+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): process_csv_files> on 2024-04-28 17:35:29.421487+00:00
[2024-04-28T17:40:38.335+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=228) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-28T17:40:38.337+0000] {standard_task_runner.py:63} INFO - Started process 230 to run task
[2024-04-28T17:40:38.338+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_processing_dag', 'process_csv_files', 'manual__2024-04-28T17:35:29.421487+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/csv_dags.py', '--cfg-path', '/tmp/tmpx715vu3r']
[2024-04-28T17:40:38.341+0000] {standard_task_runner.py:91} INFO - Job 104: Subtask process_csv_files
[2024-04-28T17:40:38.404+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_processing_dag.process_csv_files manual__2024-04-28T17:35:29.421487+00:00 [running]> on host 4cdb6c1dd19f
[2024-04-28T17:40:38.529+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_processing_dag' AIRFLOW_CTX_TASK_ID='process_csv_files' AIRFLOW_CTX_EXECUTION_DATE='2024-04-28T17:35:29.421487+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-28T17:35:29.421487+00:00'
[2024-04-28T17:40:38.533+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-28T17:40:39.615+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-28T17:40:39.622+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-28T17:40:39.796+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=csv_processing_dag, task_id=process_csv_files, execution_date=20240428T173529, start_date=20240428T174038, end_date=20240428T174039
[2024-04-28T17:40:39.853+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-28T17:40:39.878+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-28T17:40:39.883+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
